FROM couchdb:2.3
COPY docker.ini /opt/couchdb/etc/local.d/
# RUN apt-get update && apt-get install -y curl gnupg
# RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash -
# RUN apt-get install -y nodejs
# RUN npm install -g add-cors-to-couchdb